kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: show-doc-diff
  pull: always
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.12.2
  commands:
    - terraform-docs md . > /tmp/generated.md
    - echo "===== README TF_DOCS BLOCK ====="
    - awk '/<!-- BEGIN_TF_DOCS -->/{flag=1;next} /<!-- END_TF_DOCS -->/{flag=0;exit} flag{print}' README.md > /tmp/readme_block.md || true
    - echo "===== GENERATED ====="
    - cat /tmp/generated.md
    - echo "===== DIFF ====="
    - diff -u /tmp/readme_block.md /tmp/generated.md || true

- name: validate
  pull: always
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.12.2
  commands:
    - /acp/scripts/tf-validate.sh
  when:
    event:
      - pull_request
      - push