---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

- name: validate
  pull: always
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.12.2
  commands:
  - /acp/scripts/tf-validate.sh
  when:
    event:
    - pull_request
    - push

...
