---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: validate
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.1.7
  commands:
  - 'echo "=== DEBUG: Original README.md content ==="'
  - 'cat README.md'
  - 'echo "=== DEBUG: Running terraform-docs ==="'
  - 'cp README.md README.md.backup'
  - 'terraform-docs md --output-file README.md . || true'
  - 'echo "=== DEBUG: Generated README.md content ==="'
  - 'cat README.md'
  - 'echo "=== DEBUG: Binary diff check ==="'
  - 'cmp README.md.backup README.md || echo "Files differ"'
  - 'echo "=== DEBUG: Hex dump comparison ==="'
  - 'xxd README.md.backup | head -5'
  - 'xxd README.md | head -5'
  - 'echo "=== DEBUG: Contents of tf-validate.sh script ==="'
  - 'cat /acp/scripts/tf-validate.sh'
  - 'echo "=== DEBUG: Manually simulating validation script logic ==="'
  - 'tempfile_debug=$(mktemp /tmp/docs.XXXXXXXXX)'
  - 'cp README.md $tempfile_debug'
  - 'echo "Temp file before terraform-docs:"'
  - 'head -5 $tempfile_debug'
  - 'terraform-docs md --output-file $tempfile_debug .'
  - 'echo "Temp file after terraform-docs:"'
  - 'head -5 $tempfile_debug'
  - 'echo "=== Diff between README and temp file ==="'
  - 'diff -u README.md $tempfile_debug || echo "Files differ as shown above"'
  - 'echo "=== DEBUG: Check main.tf before validation script runs ==="'
  - 'head -10 main.tf'
  - 'echo "=== Now running actual validation ==="'
  - '/acp/scripts/tf-validate.sh || true'
  - 'echo "=== DEBUG: Check main.tf after validation script runs ==="'
  - 'head -10 main.tf'
  - 'echo "=== DEBUG: Running terraform-docs ONE MORE TIME after validation ==="'
  - 'tempfile_final=$(mktemp /tmp/docs.XXXXXXXXX)'
  - 'cp README.md $tempfile_final'
  - 'terraform-docs md --output-file $tempfile_final .'
  - 'echo "=== Final diff ==="'
  - 'diff -u README.md $tempfile_final || echo "NOW files differ!"'
  when:
    event:
    - pull_request
    - push

...
