---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: validate
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.1.7
  commands:
  - 'echo "=== DEBUG: Original README.md content ==="'
  - 'cat README.md'
  - 'echo "=== DEBUG: Running terraform-docs ==="'
  - 'cp README.md README.md.backup'
  - 'terraform-docs md --output-file README.md . || true'
  - 'echo "=== DEBUG: Generated README.md content ==="'
  - 'cat README.md'
  - 'echo "=== DEBUG: Binary diff check ==="'
  - 'cmp README.md.backup README.md || echo "Files differ"'
  - 'echo "=== DEBUG: Hex dump comparison ==="'
  - 'xxd README.md.backup | head -5'
  - 'xxd README.md | head -5'
  - 'echo "=== DEBUG: Contents of tf-validate.sh script ==="'
  - 'cat /acp/scripts/tf-validate.sh'
  - 'echo "=== DEBUG: Simulating what tf-validate.sh does ==="'
  - 'cp README.md README.md.before-validate'
  - 'echo "=== Now running actual validation ==="'
  - '/acp/scripts/tf-validate.sh'
  - 'echo "=== DEBUG: What did validation script change? ==="'
  - 'diff -u README.md.before-validate README.md || echo "No changes by validate script"'
  when:
    event:
    - pull_request
    - push

...
